name: Ansible
on:
  push:
    branches:
    - main
  
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
        with:
          args: "ansible"
          
  deployAnsible:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: python.yml
          directory: ansible
        # key: ${{ secrets.SSH_KEY }}
          
      - name: Checking adjusted Python venvs
        run: ls -la "/opt/python_venvs/"
